DROP MATERIALIZED VIEW IF EXISTS builders_7d;
DROP MATERIALIZED VIEW IF EXISTS builders_30d;

DROP MATERIALIZED VIEW IF EXISTS censored_transactions_7d;
DROP MATERIALIZED VIEW IF EXISTS censored_transactions_30d;

DROP MATERIALIZED VIEW IF EXISTS inclusion_delay_7d;
DROP MATERIALIZED VIEW IF EXISTS inclusion_delay_30d;

DROP MATERIALIZED VIEW IF EXISTS operators_7d;
DROP MATERIALIZED VIEW IF EXISTS operators_30d;

DROP MATERIALIZED VIEW IF EXISTS top_7d;
DROP MATERIALIZED VIEW IF EXISTS top_30d;
