ALTER TABLE builder_pubkeys ADD COLUMN builder_name text;

UPDATE builder_pubkeys SET builder_name = 'Flashbots' WHERE builder_id = 'flashbots';
UPDATE builder_pubkeys SET builder_name = 'builder0x69' WHERE builder_id = '0x69';
UPDATE builder_pubkeys SET builder_name = 'beaverbuild' WHERE builder_id = 'beaver';
UPDATE builder_pubkeys SET builder_name = 'bloXroute' WHERE builder_id = 'bloxroute';
UPDATE builder_pubkeys SET builder_name = 'rsync-builder' WHERE builder_id = 'rsync';
UPDATE builder_pubkeys SET builder_name = 'Blocknative' WHERE builder_id = 'blocknative';
UPDATE builder_pubkeys SET builder_name = 'manta-builder' WHERE builder_id = 'manta';
UPDATE builder_pubkeys SET builder_name = 'BuildAI' WHERE builder_id = 'ai';
UPDATE builder_pubkeys SET builder_name = 'eth-builder' WHERE builder_id = 'eth';
UPDATE builder_pubkeys SET builder_name = 'lightspeedbuilder' WHERE builder_id = 'lightspeed';
UPDATE builder_pubkeys SET builder_name = 'antbuilder' WHERE builder_id = 'ant';
UPDATE builder_pubkeys SET builder_name = 'Rick Astley' WHERE builder_id = 'rick';
UPDATE builder_pubkeys SET builder_name = 'Eden' WHERE builder_id = 'eden';
UPDATE builder_pubkeys SET builder_name = 'finest artisanal blocks' WHERE builder_id = 'finest';
UPDATE builder_pubkeys SET builder_name = 'Payload' WHERE builder_id = 'payload';
UPDATE builder_pubkeys SET builder_name = 'bob the builder' WHERE builder_id = 'bob';
UPDATE builder_pubkeys SET builder_name = 'It''s Free Real Estate' WHERE builder_id = 'estate';
UPDATE builder_pubkeys SET builder_name = 'Titan' WHERE builder_id = 'titan';
UPDATE builder_pubkeys SET builder_name = 'n!' WHERE builder_id = 'nfactorial';
UPDATE builder_pubkeys SET builder_name = 'Manifold' WHERE builder_id = 'manifold';
UPDATE builder_pubkeys SET builder_name = 'mars' WHERE builder_id = 'mars';
UPDATE builder_pubkeys SET builder_name = 'I can haz block?' WHERE builder_id = 'haz';
UPDATE builder_pubkeys SET builder_name = 'Gambit' WHERE builder_id = 'gambit';
UPDATE builder_pubkeys SET builder_name = 'miao' WHERE builder_id = 'miao';
UPDATE builder_pubkeys SET builder_name = 'NeoConstruction' WHERE builder_id = 'neo';
UPDATE builder_pubkeys SET builder_name = 'smithboth' WHERE builder_id = 'smithbot';
UPDATE builder_pubkeys SET builder_name = 'Merkle' WHERE builder_id = 'merkle';
