REFRESH MATERIALIZED VIEW builders_7d;
REFRESH MATERIALIZED VIEW builders_30d;

REFRESH MATERIALIZED VIEW censored_transactions_7d;
REFRESH MATERIALIZED VIEW censored_transactions_30d;

REFRESH MATERIALIZED VIEW inclusion_delay_7d;
REFRESH MATERIALIZED VIEW inclusion_delay_30d;

REFRESH MATERIALIZED VIEW operators_7d;
REFRESH MATERIALIZED VIEW operators_30d;
REFRESH MATERIALIZED VIEW operators_all;

REFRESH MATERIALIZED VIEW top_7d;
REFRESH MATERIALIZED VIEW top_30d;
